### ISSUE TITLE
bug: sending a message is duplicated in web UI

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#170]
Flaky bug, happens 20-40% of the time. Might be related to #169 

To repro: 
1. start a new chat session
2. send a query, e.g. "hi"
3. see that the user message is sent twice 
4. 
![Screenshot 2023-09-12 at 8 51 24 PM](https://github.com/janhq/jan/assets/69952136/8be402cc-b137-4bcf-8d3a-6c0f19ffae53)

logs
```sh
d from client (via refresh/close) Address(host='::1', port=54427)
ERROR:    ASGI callable returned without completing response.
INFO:     ::1:54430 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/llama_cpp/server/app.py", line 261, in custom_route_handler
    json_body = await request.json()
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/requests.py", line 244, in json
    self._json = json.loads(body)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:     ::1:54428 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/llama_cpp/server/app.py", line 261, in custom_route_handler
    json_body = await request.json()
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/site-packages/starlette/requests.py", line 244, in json
    self._json = json.loads(body)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/nicolezhu/mambaforge/envs/jan/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by 0xSage** [comment]
no longer rel
