### ISSUE TITLE
bug: "docker compose --profile cpu-fs up -d" on a clean git checkout does not result in a usable server

### ISSUE THREAD

**Issue by manschwetus** [janhq/jan#2394]
**Describe the bug**
Running "docker compose --profile cpu-fs up -d" on a fresh git checkout does not result in a usable server.
Opening "http://localhost:3000/" as documented results in an error, on console I get:
```
TypeError: Cannot read properties of undefined (reading 'onUserSubmitQuickAsk')
    at QuickAskListener (layout-94eca8d8fb56f4cf.js:540:24)
    at Mf (618f8807-0d93a2008dce78ef.js:115:143)
    at Nk (618f8807-0d93a2008dce78ef.js:279:338)
    at Jk (618f8807-0d93a2008dce78ef.js:268:321)
    at Ik (618f8807-0d93a2008dce78ef.js:266:30)
    at df (618f8807-0d93a2008dce78ef.js:265:315)
    at ef (618f8807-0d93a2008dce78ef.js:259:94)
    at qf (618f8807-0d93a2008dce78ef.js:257:367)
    at MessagePort.P (835-c87486d6303e8ccc.js:6029:252)
```

**Steps to reproduce**
1. git clone repository
2. cd to cloned directory
3. run "docker compose --profile cpu-fs up -d"
4. wait
5. open "http://localhost:3000/" in webbrowser
6. Get page stating "Application error: a client-side exception has occurred (see the browser console for more information)."
7. Check java script console for error

**Expected behavior**
See browser interface of home server

**Environment details**
- Operating System: Gentoo Linux
- Jan Version: git - dev
- Processor: AMD Ryzen 7 8700G
- RAM: 64GB

**Comment by louis-jan** [comment]
Thank you. We will check it as soon as possible.

**Comment by louis-jan** [comment]
Hi @manschwetus. Could you please help pull the latest dev and try whether the fix is working?

**Comment by manschwetus** [comment]
works now
