### ISSUE TITLE
bug: "Import Model" Button and Drag-and-Drop Not Working

### ISSUE THREAD

**Issue by puff-dayo** [janhq/jan#2837]
**Describe the bug**
Encountering an issue when attempting to import a model. It seems like the button is not responding. Additionally, when trying to import a gguf file by dragging and dropping it, nothing seems to happen as well.

**Steps to reproduce**
Click the "Click to upload" button, the file selection dialog does not pop up as expected. 
Neither when dragging and dropping.

**Screenshots**
![2024-04-27 21-41-27](https://github.com/janhq/jan/assets/84665734/6fa47fff-2fd3-45d5-85ba-0d3130425ce2)

**Environment details**
- Operating System: Debian12 GNOME
- Jan Version: 0.4.12
- Processor: Intel m3-6Y30
- RAM: 4GB

**Logs**
Upon inspecting the Electron developer tools console:
```
835-c87486d6303e8ccc.js:213 Error: Error invoking remote method 'joinPath': TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
push.9122.window.console.error @ 835-c87486d6303e8ccc.js:213
index.js:1006 Error: Error invoking remote method 'readFileSync': Error: ENOENT: no such file or directory, open '/home/username/jan/settings/@janhq/conversational-extension/settings.json'
(anonymous) @ index.js:1006
index.js:927 Error: Error invoking remote method 'readFileSync': Error: ENOENT: no such file or directory, open '/home/username/jan/settings/@janhq/model-extension/settings.json'
(anonymous) @ index.js:927
345-7c0d73c85fa4f257.js:2691 System monitoring extension not found
systemInformation @ 345-7c0d73c85fa4f257.js:2691
page-5d76c20d652fc26c.js:4629 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'osInfo')
    at page-5d76c20d652fc26c.js:4629:86
345-7c0d73c85fa4f257.js:2691 System monitoring extension not found
systemInformation @ 345-7c0d73c85fa4f257.js:2691
page-5d76c20d652fc26c.js:4629 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'osInfo')
    at page-5d76c20d652fc26c.js:4629:86
345-7c0d73c85fa4f257.js:2691 System monitoring extension not found
systemInformation @ 345-7c0d73c85fa4f257.js:2691
systemInformation @ 345-7c0d73c85fa4f257.js:531
(anonymous) @ page-5d76c20d652fc26c.js:4629
Hi @ 618f8807-0d93a2008dce78ef.js:209
Ni @ 618f8807-0d93a2008dce78ef.js:210
Oi @ 618f8807-0d93a2008dce78ef.js:210
Nn @ 618f8807-0d93a2008dce78ef.js:347
Zm @ 618f8807-0d93a2008dce78ef.js:348
(anonymous) @ 618f8807-0d93a2008dce78ef.js:359
Ak @ 618f8807-0d93a2008dce78ef.js:261
ll @ 618f8807-0d93a2008dce78ef.js:304
zm @ 618f8807-0d93a2008dce78ef.js:351
xm @ 618f8807-0d93a2008dce78ef.js:326
wm @ 618f8807-0d93a2008dce78ef.js:325
page-5d76c20d652fc26c.js:4629 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'osInfo')
    at page-5d76c20d652fc26c.js:4629:86
(anonymous) @ page-5d76c20d652fc26c.js:4629
await in (anonymous) (async)
Hi @ 618f8807-0d93a2008dce78ef.js:209
Ni @ 618f8807-0d93a2008dce78ef.js:210
Oi @ 618f8807-0d93a2008dce78ef.js:210
Nn @ 618f8807-0d93a2008dce78ef.js:347
Zm @ 618f8807-0d93a2008dce78ef.js:348
(anonymous) @ 618f8807-0d93a2008dce78ef.js:359
Ak @ 618f8807-0d93a2008dce78ef.js:261
ll @ 618f8807-0d93a2008dce78ef.js:304
zm @ 618f8807-0d93a2008dce78ef.js:351
xm @ 618f8807-0d93a2008dce78ef.js:326
wm @ 618f8807-0d93a2008dce78ef.js:325
```

**Comment by Van-QA** [comment]
hi @puff-dayo, can you try the factory reset setting in the Jan app and see if the issue is resolved?
![image](https://github.com/janhq/jan/assets/64197333/3d9e0a1a-8929-46b9-a63e-4c3a0da155f6)
