### ISSUE TITLE
bug: Jan won't start on windows 11 SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by secchipietro04** [janhq/jan#3135]
### #

- [X] I have searched the existing issues

### Current behavior

Jan won't start, the process spawns but remains hanging.
I did find a fix, for some reason inside extensions folder (in User/jan) the file extensions.json was blank, i just had to place a {} and now it works.

### Minimum reproduction step

Start Jan, won't start

### Expected behavior

Starts

### Screenshots / Logs

D:\programmi\Jan>
(node:21988) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at useExtensions (D:\programmi\Jan\resources\app.asar\node_modules\@janhq\core\dist\node\index.cjs.js:562:27)
    at init (D:\programmi\Jan\resources\app.asar\node_modules\@janhq\core\dist\node\index.cjs.js:501:16)
    at D:\programmi\Jan\resources\app.asar\build\utils\extension.js:43:25
    at step (D:\programmi\Jan\resources\app.asar\build\utils\extension.js:33:23)
    at Object.next (D:\programmi\Jan\resources\app.asar\build\utils\extension.js:14:53)
    at D:\programmi\Jan\resources\app.asar\build\utils\extension.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\programmi\Jan\resources\app.asar\build\utils\extension.js:4:12)
    at setupExtensions (D:\programmi\Jan\resources\app.asar\build\utils\extension.js:41:44)
(Use `Jan --trace-warnings ...` to show where the warning was created)
(node:21988) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

### Jan version

0.5.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Environment details

MSI laptop
16 GB ram
i7 8750H
1060 6GB

**Comment by Van-QA** [comment]
hi @secchipietro04,
Gl‌‌ad to he‌ar that you was able to resolve the issu‌e.
Can you try ‌wiping the extensions folder and see if the exten‌sions.json updated with any value? (after restarted Jan)
If so, the issu‌e must be related to the extensions folder update
