### ISSUE TITLE
bug: [Unknown language: `groovy` is not registered]

### ISSUE THREAD

**Issue by erayerdin** [janhq/jan#4203]
### Jan version

0.5.10

### Describe the Bug

The app does not open up after the update.

### Steps to Reproduce

1. Update the app.
2. Reload the app.
3. It crashes.

### Screenshots / Logs

![image](https://github.com/user-attachments/assets/4fe48436-6ad5-48b6-9492-1cd74f25ea17)

```
Error: Unknown language: `groovy` is not registered
    at FormattedError (file:///opt/Jan/resources/app.asar/renderer/_next/static/chunks/68-bd3478242e7278f4.js:118433:12)
    at Object.highlight (file:///opt/Jan/resources/app.asar/renderer/_next/static/chunks/68-bd3478242e7278f4.js:118487:11)
    at file:///opt/Jan/resources/app.asar/renderer/_next/static/chunks/68-bd3478242e7278f4.js:120953:22
    at overload (file:///opt/Jan/resources/app.asar/renderer/_next/static/chunks/68-bd3478242e7278f4.js:120834:16)
    at node (element<code>) (file:///opt/Jan/resources/app.asar/renderer/_next/static/chunks/68-bd3478242e7278f4.js:120607:31)
    at node (element<pre>) (file:///opt/Jan/resources/app.asar/renderer/_next/static/chunks/68-bd3478242e7278f4.js:120624:79)
    at node (element<li>) (file:///opt/Jan/resources/app.asar/renderer/_next/static/chunks/68-bd3478242e7278f4.js:120624:79)
    at node (element<ol>) (file:///opt/Jan/resources/app.asar/renderer/_next/static/chunks/68-bd3478242e7278f4.js:120624:79)
    at node (root) (file:///opt/Jan/resources/app.asar/renderer/_next/static/chunks/68-bd3478242e7278f4.js:120624:79)
    at visitParents (file:///opt/Jan/resources/app.asar/renderer/_next/static/chunks/68-bd3478242e7278f4.js:120566:35)
```

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

**Comment by erayerdin** [comment]
Maybe related to #4195 ?

**Comment by erayerdin** [comment]
Or possibly related to this: https://github.com/orgs/remarkjs/discussions/1013

**Comment by suda** [comment]
Have the same problem after updating but with:

```
Unknown language: `powershell` is not registered
```

One of the latest threads was indeed about `powershell` therefore I suspect it has something to do with `remarkjs` as mentioned by Eray.
