### ISSUE TITLE
bug: [0.5.10] Code highlighting is broken for certain programming languages, causing Jan to crash

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4215]
### Jan version

0.5.10

### Describe the Bug

https://discord.com/channels/1107178041848909847/1313560281846251531
https://discord.com/channels/1107178041848909847/1313779900267757568

Code highlighting is broken for certain programming languages, causing Jan to crash or display errors. The error appears as "Unknown language: X is not registered" where X is the language being used. This affects multiple users across different operating systems and setups.

**Specific examples:**
- Delphi code displays error: "Unknown language: del is not registered"
- PowerShell code fails with error: "Unknown language: 'powers' is not registered" 
- The issue appears to be related to code block rendering in the chat interface

```
Error: Unknown language: `<|endoftext|>` is not registered
Error: Unknown language: `<|endoftext|>` is not registered
    at FormattedError (file:///Applications/Jan.app/Contents/Resources/app.asar/renderer/_next/static/chunks/19-c74c79ae113d7ad7.js:118331:12)
    at Object.highlight (file:///Applications/Jan.app/Contents/Resources/app.asar/renderer/_next/static/chunks/19-c74c79ae113d7ad7.js:118385:11)
    at file:///Applications/Jan.app/Contents/Resources/app.asar/renderer/_next/static/chunks/19-c74c79ae113d7ad7.js:120851:22
    at overload (file:///Applications/Jan.app/Contents/Resources/app.asar/renderer/_next/static/chunks/19-c74c79ae113d7ad7.js:120732:16)
    at node (element<code>) (file:///Applications/Jan.app/Contents/Resources/app.asar/renderer/_next/static/chunks/19-c74c79ae113d7ad7.js:120505:31)
    at node (element<pre>) (file:///Applications/Jan.app/Contents/Resources/app.asar/renderer/_next/static/chunks/19-c74c79ae113d7ad7.js:120522:79)
    at node (root) (file:///Applications/Jan.app/Contents/Resources/app.asar/renderer/_next/static/chunks/19-c74c79ae113d7ad7.js:120522:79)
    at visitParents (file:///Applications/Jan.app/Contents/Resources/app.asar/renderer/_next/static/chunks/19-c74c79ae113d7ad7.js:120464:35)
    at visit (file:///Applications/Jan.app/Contents/Resources/app.asar/renderer/_next/static/chunks/19-c74c79ae113d7ad7.js:120724:7)
    at file:///Applications/Jan.app/Contents/Resources/app.asar/renderer/_next/static/chunks/19-c74c79ae113d7ad7.js:120815:5
```

### Workaround
Some users report that deleting the problematic thread fixes the immediate crash, but the underlying code highlighting issue persists for new conversations.

### Steps to Reproduce

1. Open Jan v0.5.10
2. Try to display code in affected languages (Delphi, PowerShell)
3. Alternatively, use chat messages containing custom markup tags
4. Observe error messages or application crash

### Screenshots / Logs

Windows 10
   - CPU: i7 8700
   - GPU: Nvidia 3060 ti 8gig
   - Using: llama 3 8b instruct q4
   
MacOS (M3 Max, latest OS)
   - Error occurs with Mistral7b Instruct model
   - Issue appears when using markup tags to separate instructions

### What is your OS?

- [X] MacOS
- [X] Windows
- [X] Linux

**Comment by imtuyethan** [comment]
<img width="917" alt="Screenshot 2024-12-04 at 7 50 23 PM" src="https://github.com/user-attachments/assets/7454665d-a50d-45f3-ad4f-78f6ac8330d4">
<img width="913" alt="Screenshot 2024-12-04 at 7 50 17 PM" src="https://github.com/user-attachments/assets/fa64fe87-3f5f-4b68-9804-5d391a230130">
![Uploading Screenshot 2024-12-04 at 7.50.50 PM.png…]()
